# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d698736f6bdebd8679ddf9a61cf56552c5aaa4de4cb163b7b5ca86641515229659bc63e090af191a1603df8c806587e0e7c85a16fe68539876b3bc756ce52ec

test:
  secret_key_base: 05a0390d76ad0625eb9618a82f449db8ac819e94a4d73c39575158ed47688f2ef50c33e7a05f31ae7c27c8442ad744b35857f6319918067c10268dec1cbb291b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
